### ISSUE TITLE
Add laptop-specific packages

### ISSUE THREAD

**Issue by erazemkokot** [AnarchyLinux/installer#826]
A new option should be added to the installation (maybe after asking if you want wifi support) - laptop specific software and configs, such as `tlp` and if a supported Thinkpad laptop is detected also `acpi-call-dkms` and similar (battery control). Another possibly useful tool would be `powertop`.

### Todo:

* [ ] if LAPTOP=true add tlp to packages
* [ ] option for tlp-rdw (needs to [enable separate services](https://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#arch))
* [ ] enable tlp service after installation (maybe separate function "cleanup")

**Comment by JustMeErazem** [comment]
Todo:

* [ ] if LAPTOP=true add tlp to packages
* [ ] option for tlp-rdw (needs to [enable separate services](https://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#arch))
* [ ] enable tlp service after installation (maybe separate function "cleanup")
